package:
  name: durationpy
  version: "0.3"

source:
  fn: durationpy-0.3.tar.gz
  url: https://pypi.python.org/packages/ed/c7/3617c9c9de2e8429fe8a975af99f9539181c53db3d78438cfebabcd9dbb8/durationpy-0.3.tar.gz
  md5: b24e3ee45d1c8c3854da2d61ced5ca39
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - durationpy = durationpy:main
    #
    # Would create an entry point called durationpy that calls durationpy.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python

  run:
    - python

test:
  # Python imports
  imports:
    - durationpy

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/icholy/durationpy
  license: MIT
  summary: "Module for converting between datetime.timedelta and Go's Duration strings."
  license_family: MIT

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
