{% set version = "0.39.1.dev" %}

package:
  name: zappa
  version: {{ version }}

source:
  path: /Users/carettem/github/mathieu1/zappa/

build:
  entry_points:
    - zappa=zappa.cli:handle
    - z=zappa.cli:handle
  number: 1
  script: pip install --no-deps .

requirements:
  build:
    - python
    - setuptools
    - argcomplete ==1.8.2
    - base58 ==0.2.4
    - botocore ==1.5.27
    - boto3 ==1.4.4
    - docutils >=0.12
    - durationpy ==0.3
    - futures ==3.0.5
    - hjson ==2.0.2
    - jmespath ==0.9.2
    - kappa ==0.6.0
    - lambda-packages ==0.14.2
    - python-dateutil ==2.6.0
    - python-slugify ==1.2.1
    - pyyaml ==3.12
    - requests >=2.10.0
    - six ==1.10.0
    - toml ==0.9.2
    - tqdm ==4.11.2
    - troposphere >=1.9.0
    - werkzeug ==0.12
    - wheel ==0.29.0
    - wsgi-request-logger ==0.4.6

  run:
    - python
    - argcomplete ==1.8.2
    - base58 ==0.2.4
    - botocore ==1.5.27
    - boto3 ==1.4.4
    - docutils >=0.12
    - durationpy ==0.3
    - futures ==3.0.5
    - hjson ==2.0.2
    - jmespath ==0.9.2
    - kappa ==0.6.0
    - lambda-packages ==0.14.2
    - python-dateutil ==2.6.0
    - python-slugify ==1.2.1
    - pyyaml ==3.12
    - requests >=2.10.0
    - six ==1.10.0
    - toml ==0.9.2
    - tqdm ==4.11.2
    - troposphere >=1.9.0
    - werkzeug ==0.12
    - wheel ==0.29.0
    - wsgi-request-logger ==0.4.6

test:
  imports:
    - zappa

  commands:
    - zappa --help
    - z --help

  requires:
    - coveralls
    - django
    - mock
    - nose
    - nose-timer
    - placebo

about:
  home: https://github.com/Miserlou/Zappa
  license: Apache Software License
  summary: 'Serverless WSGI With AWS Lambda + API Gateway'
