package:
  name: kappa
  version: "0.6.0"

source:
  fn: kappa-0.6.0.tar.gz
  url: https://pypi.python.org/packages/ee/fa/1b8328d2199520ef5a257f8a2e9315ed0b0194e353a152ca1959490dfbc8/kappa-0.6.0.tar.gz
  md5: 799941ab585985aace9317289b4e2346
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - pip
    - pyyaml >=3.11
    - boto3 >=1.2.3
    - click >=5.1
    - placebo >=0.8.1
  run:
    - python
    - pyyaml >=3.11
    - boto3 >=1.2.3
    - click >=5.1
    - placebo >=0.8.1
test:
  # Python imports
  imports:
    - kappa

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - kappa --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

about:
  home: https://github.com/garnaat/kappa
  license: Apache Software License
  summary: 'A CLI tool for AWS Lambda developers'
  license_family: Apache

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
