package:
  name: placebo
  version: "0.8.1"

source:
  fn: placebo-0.8.1.tar.gz
  url: https://files.pythonhosted.org/packages/89/c7/809e349d224ea5d7d5d5ad470e75634e88a43ba4ab84a08f7734ab23d4e6/placebo-0.8.1.tar.gz
  md5: 349657cef05afc1b2eebed6dc6acf625
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - placebo = placebo:main
    #
    # Would create an entry point called placebo that calls placebo.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - placebo

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/garnaat/placebo
  license: Apache Software License
  summary: 'Make boto3 calls that look real but have no effect'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
