package:
  name: awacs
  version: "0.6.1"

source:
  fn: awacs-0.6.1.tar.gz
  url: https://pypi.python.org/packages/c5/b9/f7fb0a5c5c796d52a0a4ee993639b09004048cc0f466f9f6dd8bb57faed3/awacs-0.6.1.tar.gz
  md5: c8bb108927ea52f93000b9c31e58319a
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - awacs = awacs:main
    #
    # Would create an entry point called awacs that calls awacs.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - awacs
    - awacs.helpers
    - tests

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/cloudtools/awacs
  license: New BSD license
  summary: 'AWS Access Policy Language creation library'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
