{% set version = "0.8.1" %}

package:
  name: placebo
  version: {{ version }}

source:
  fn: placebo-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/placebo/placebo-{{ version }}.tar.gz
  md5: 349657cef05afc1b2eebed6dc6acf625

build:
  number: 0
  script: pip install --no-deps .

requirements:
  build:
    - python
    - pip

  run:
    - python

test:
  imports:
    - placebo
  requires:
    - botocore

about:
  home: https://github.com/garnaat/placebo
  license: Apache Software License
  summary: 'Make boto3 calls that look real but have no effect'