package:
  name: toml
  version: "0.9.2"

source:
  fn: toml-0.9.2.tar.gz
  url: https://pypi.python.org/packages/5c/b2/8a18ced00a43f2cc5261f9ac9f1c94621251400a80db1567177719355177/toml-0.9.2.tar.gz
  md5: 910a9573116c91d63e132741183c8a80

requirements:
  build:
    - python

  run:
    - python
about:
  home: https://github.com/uiri/toml
  license: "License :: OSI Approved :: MIT License"
  summary: "Python Library for Tom's Obvious, Minimal Language"
  license_family: MIT