package:
  name: zappa
  version: "0.32.1"

source:
  fn: zappa-0.32.1.tar.gz
  url: https://pypi.python.org/packages/a4/77/3a358b3cf92b4a28628544ba69b312d24fc5485c7ab9c623cea7e0176997/zappa-0.32.1.tar.gz
  md5: b1594a7f7248c7d149193778ddbff21b
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - zappa = zappa:main
    #
    # Would create an entry point called zappa that calls zappa.main()

    - zappa=zappa.cli:handle
    - z=zappa.cli:handle

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - argcomplete ==1.7.0
    - base58 ==0.2.4
    - botocore ==1.4.87
    - boto3 ==1.4.2
    - docutils >=0.12
    - futures ==3.0.5
    - hjson ==2.0.2
    - jmespath ==0.9.0
    - kappa ==0.6.0
    - lambda_packages ==0.11.0
    - python-dateutil ==2.6.0
    - python-slugify ==1.2.1
    - pyyaml ==3.12
    - requests >=2.10.0
    - six ==1.10.0
    - toml ==0.9.2
    - tqdm ==4.10.0
    - troposphere >=1.9.0
    - werkzeug ==0.11.11
    - wheel ==0.29.0
    - wsgi-request-logger ==0.4.6

  run:
    - python
    - argcomplete ==1.7.0
    - base58 ==0.2.4
    - botocore ==1.4.87
    - boto3 ==1.4.2
    - docutils >=0.12
    - futures ==3.0.5
    - hjson ==2.0.2
    - jmespath ==0.9.0
    - kappa ==0.6.0
    - lambda-packages ==0.11.0
    - python-dateutil ==2.6.0
    - python-slugify ==1.2.1
    - pyyaml ==3.12
    - requests >=2.10.0
    - six ==1.10.0
    - toml ==0.9.2
    - tqdm ==4.10.0
    - troposphere >=1.9.0
    - werkzeug ==0.11.11
    - wheel ==0.29.0
    - wsgi-request-logger ==0.4.6

test:
  # Python imports
  imports:
    - zappa

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - zappa --help
    - z --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  requires:
    - coveralls ==1.1
    - django ==1.10.4
    - mock ==2.0.0
    - nose ==1.3.7
    - nose-timer ==0.6.0
    - placebo ==0.8.1
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/Miserlou/Zappa
  license: Apache Software License
  summary: 'Server-less Python Web Services for AWS Lambda and API Gateway'
  license_family: APACHE

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
