package:
  name: werkzeug
  version: "0.11.15"

source:
  fn: Werkzeug-0.11.15.tar.gz
  url: https://pypi.python.org/packages/fe/7f/6d70f765ce5484e07576313897793cb49333dd34e462488ee818d17244af/Werkzeug-0.11.15.tar.gz
  md5: cb4010478dd33905f95920e4880204a2
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - werkzeug = werkzeug:main
    #
    # Would create an entry point called werkzeug that calls werkzeug.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - werkzeug
    - werkzeug.contrib
    - werkzeug.debug

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://werkzeug.pocoo.org/
  license: BSD License
  summary: 'The Swiss Army knife of Python web development'
  license_family: BSD

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
